// Code generated by Kitex. DO NOT EDIT.
//
// 这是 Kitex 生成的服务接口定义
// 实际项目中由 kitex 工具自动生成

package recommendation

import (
	"context"
)

// RecommendationService 推荐服务接口
//
// 这是 RPC 服务的接口定义，由 Kitex 根据 Thrift IDL 生成。
//
// 服务接口 vs Handler 实现：
// - 服务接口：定义 RPC 方法签名（由 Kitex 生成）
// - Handler 实现：实现具体的业务逻辑（由开发者编写）
//
// 在 DDD 架构中的位置：
// 这个接口属于接口层（Interface Layer），是外部世界与应用的契约。
//
// 实际使用：
// 1. Kitex 生成这个接口
// 2. 开发者实现 RecommendationHandler（在 interface/handler 中）
// 3. Kitex 框架调用 Handler 处理请求
type RecommendationService interface {
	// GetFollowingBasedRecommendations 获取基于关注的推荐
	//
	// RPC 方法签名：
	// - ctx: 上下文，用于超时控制、链路追踪、取消传播等
	// - req: RPC 请求对象（包含用户ID和限制数量）
	// - 返回: RPC 响应对象和错误
	//
	// 完整调用流程：
	// 1. 客户端发起 RPC 调用
	// 2. Kitex 框架序列化请求
	// 3. 网络传输
	// 4. Kitex 框架反序列化请求
	// 5. 调用 Handler 实现（interface/handler）
	// 6. Handler 调用应用服务（application/service）
	// 7. 应用服务调用领域服务（domain/service）
	// 8. 领域服务执行业务逻辑
	// 9. 逐层返回结果
	// 10. Kitex 框架序列化响应
	// 11. 返回给客户端
	//
	// 在 DDD 架构中的位置：
	// 这个接口是接口层（Interface Layer）的契约，
	// 定义了外部世界如何与系统交互。
	//
	// 实际使用示例：
	//   // 客户端调用
	//   client := recommendation.NewClient("recommendation-service")
	//   req := &recommendation.GetRecommendationsRequest{
	//       UserId: 123,
	//       Limit:  10,
	//   }
	//   resp, err := client.GetFollowingBasedRecommendations(ctx, req)
	GetFollowingBasedRecommendations(ctx context.Context, req *GetRecommendationsRequest) (*GetRecommendationsResponse, error)
}
