// Code generated by Kitex. DO NOT EDIT.
//
// 这是 Kitex 根据 Thrift IDL 生成的代码
// 实际项目中应该使用 kitex 命令生成：
//   kitex -module <module_name> idl/recommendation.thrift
//
// 这里为了示例完整性，手动创建了简化版本

package recommendation

// GetRecommendationsRequest 推荐请求
//
// RPC 请求对象 vs 领域对象：
// - RPC 请求：用于网络传输，包含序列化标签
// - 领域对象：用于业务逻辑，不包含技术细节
//
// 为什么需要分离？
// 1. 协议独立：业务逻辑不依赖 RPC 框架
// 2. 版本管理：RPC 接口可以独立演进
// 3. 类型转换：RPC 的 int64 转换为领域的 UserID
type GetRecommendationsRequest struct {
	UserId int64 `thrift:"user_id,1,required" json:"user_id"`
	Limit  int32 `thrift:"limit,2,optional" json:"limit,omitempty"`
}

// GetRecommendationsResponse 推荐响应
type GetRecommendationsResponse struct {
	Recommendations []*UserRecommendation `thrift:"recommendations,1,required" json:"recommendations"`
}

// UserRecommendation 用户推荐
//
// 这是 RPC 层的数据结构，对应前端展示需要的数据。
// 它与领域层的 UserRecommendation 聚合是不同的：
// - 领域聚合：包含业务逻辑和行为
// - RPC 结构：只包含数据，用于传输
type UserRecommendation struct {
	UserId      int64   `thrift:"user_id,1,required" json:"user_id"`
	Username    string  `thrift:"username,2,required" json:"username"`
	Avatar      string  `thrift:"avatar,3,required" json:"avatar"`
	Bio         string  `thrift:"bio,4,optional" json:"bio,omitempty"`
	Reason      string  `thrift:"reason,5,required" json:"reason"`
	Score       int32   `thrift:"score,6,required" json:"score"`
	RecentPosts []*Post `thrift:"recent_posts,7,required" json:"recent_posts"`
}

// Post 帖子
//
// RPC 层的 Post vs 领域层的 Post 实体：
// - RPC Post：简单的数据结构，用于传输
// - 领域 Post：实体对象，有 ID、行为方法
type Post struct {
	PostId    int64  `thrift:"post_id,1,required" json:"post_id"`
	Content   string `thrift:"content,2,required" json:"content"`
	CreatedAt string `thrift:"created_at,3,required" json:"created_at"`
}

// NewGetRecommendationsRequest 创建请求对象
func NewGetRecommendationsRequest() *GetRecommendationsRequest {
	return &GetRecommendationsRequest{
		Limit: 10, // 默认值
	}
}

// NewGetRecommendationsResponse 创建响应对象
func NewGetRecommendationsResponse() *GetRecommendationsResponse {
	return &GetRecommendationsResponse{
		Recommendations: make([]*UserRecommendation, 0),
	}
}

// GetUserId 获取用户ID
func (p *GetRecommendationsRequest) GetUserId() int64 {
	return p.UserId
}

// GetLimit 获取限制数量
func (p *GetRecommendationsRequest) GetLimit() int32 {
	if p.Limit == 0 {
		return 10
	}
	return p.Limit
}

// GetRecommendations 获取推荐列表
func (p *GetRecommendationsResponse) GetRecommendations() []*UserRecommendation {
	return p.Recommendations
}
